import { AccessBar, latencyBar, statusBar } from "./bars";

export const mockAccessBars: AccessBar[] = [
  {
    name: "DE • Germany Tunnel",
    country: "DE",
    percentage: 75,
    site: {
      social: {
        "instagram.com": 1.67,
        "youtube.com": 0.76,
      },
      gaming: {
        "steamcommunity.com": 3.12,
      },
    },
  },
  {
    name: "US • USA Tunnel",
    country: "US",
    percentage: 50,
    site: {
      social: {
        "facebook.com": 0.456,
      },
      finance: {
        "paypal.com": 0.289,
        "coinbase.com": 5.12,
      },
    },
  },
  {
    name: "FI • Finland Tunnel",
    country: "FI",
    percentage: 100,
    site: {
      dev: {
        "github.com": 1.45,
        "gitlab.com": 0.52,
      },
      gaming: {
        "epicgames.com": 0.98,
      },
    },
  },
  {
    name: "FR • France Tunnel",
    country: "FR",
    percentage: 60,
    site: {
      social: {
        "twitter.com": 0.35,
      },
      finance: {
        "bankoffrance.fr": 0.22,
      },
      dev: {
        "stackoverflow.com": 0.41,
      },
    },
  },
];

export const mockLatencyBars: latencyBar[] = [
  {
    name: "DE • Germany Tunnel",
    country: "DE",
    site: {
      "google.com": 1.67,
      "apple.com": 0.76,
      mfst: 3.12,
      gstatic: 0.456,
    },
    latency: 0.29,
  },
  {
    name: "US • USA Tunnel",
    country: "US",
    site: {
      "google.com": 1.67,
      "apple.com": 0.76,
      mfst: 3.12,
      gstatic: 0.456,
    },
    latency: 0.79,
  },
  {
    name: "FI • Finland Tunnel",
    country: "FI",
    site: {
      "google.com": 1.67,
      "apple.com": 0.76,
      mfst: 3.12,
      gstatic: 0.456,
    },
    latency: 0.179,
  },
  {
    name: "FR • France Tunnel",
    country: "FR",
    site: {
      "google.com": 1.67,
      "apple.com": 0.76,
      mfst: 3.12,
      gstatic: 0.456,
    },
    latency: 1.79,
  },
];

export const mockStatusBars: statusBar = {
  // Finance Status Bars
  finance: [
    {
      config_name: "GERMANY TUNNEL ",
      chart: [
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.15",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.16",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.17",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.18",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.19",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.20",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.21",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.22",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.23",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.24",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.25",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.26",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
      ],
    },
    {
      config_name: "Germany Websockets",
      chart: [
        {
          timestamp: "13.14",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.15",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.16",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.17",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.18",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.20",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.21",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.22",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.23",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.24",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.25",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.26",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.27",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.28",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.29",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.30",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.31",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.32",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.33",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.34",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.35",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.36",
          slots: [
            { site_name: "Bloomberg", up: 127, color: "green" },
            { site_name: "Reuters", up: 127, color: "red" },
            { site_name: "YahooFinance", up: 0, color: "purple" },
            { site_name: "MarketWatch", up: 127, color: "cyan" },
            { site_name: "CoinDesk", up: 127, color: "white" },
            { site_name: "WallStreetJournal", up: 127, color: "orange" },
            { site_name: "FinancialTimes", up: 127, color: "brown" },
            { site_name: "Morningstar", up: 0, color: "yellow" },
            { site_name: "Zacks", up: 127, color: "brown" },
            { site_name: "SeekingAlpha", up: 127, color: "blue" },
          ],
        },
      ],
    },
  ],

  // Gaming Status Bars
  gaming: [
    {
      config_name: "FINLAND TCP",
      chart: [
        {
          timestamp: "13.14",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.15",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.16",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.17",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.18",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.19",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.20",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.21",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.22",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.23",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.24",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.25",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.26",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.27",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.28",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.29",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.30",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.31",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.32",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.33",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.34",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
      ],
    },
    {
      config_name: "FINLAND Websockets",
      chart: [
        {
          timestamp: "13.35",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.36",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.37",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.38",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.39",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.40",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.41",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.42",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.43",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.44",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.45",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.46",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.47",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.48",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.49",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.50",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.51",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.52",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.53",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.54",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.56",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.57",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.58",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.59",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.60",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Steam", up: 127, color: "green" },
            { site_name: "EpicGames", up: 127, color: "red" },
            { site_name: "Twitch", up: 127, color: "purple" },
            { site_name: "YouTubeGaming", up: 127, color: "cyan" },
            { site_name: "IGN", up: 127, color: "white" },
            { site_name: "GameSpot", up: 127, color: "orange" },
            { site_name: "Kotaku", up: 0, color: "brown" },
            { site_name: "Polygon", up: 127, color: "yellow" },
            { site_name: "PCGamer", up: 127, color: "brown" },
            { site_name: "Discord", up: 127, color: "blue" },
          ],
        },
      ],
    },
  ],

  // Dev Status Bars
  dev: [
    {
      config_name: "FINLAND TCP",
      chart: [
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.14",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
      ],
    },
    {
      config_name: "Germany Websockets",
      chart: [
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
        {
          timestamp: "13.13",
          slots: [
            { site_name: "GitHub", up: 127, color: "green" },
            { site_name: "StackOverflow", up: 127, color: "red" },
            { site_name: "GitLab", up: 127, color: "purple" },
            { site_name: "DockerHub", up: 0, color: "cyan" },
            { site_name: "npm", up: 127, color: "white" },
            { site_name: "Vercel", up: 127, color: "orange" },
            { site_name: "Netlify", up: 127, color: "brown" },
            { site_name: "MDNWebDocs", up: 127, color: "yellow" },
            { site_name: "Jira", up: 0, color: "brown" },
            { site_name: "Postman", up: 127, color: "blue" },
          ],
        },
      ],
    },
  ],

  // Social Status Bars
  social: [
    {
      config_name: "USA TUNNEL ",
      chart: [
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Facebook", up: 127, color: "red" },
            { site_name: "X", up: 127, color: "red" },
            { site_name: "Instagram", up: 127, color: "red" },
            { site_name: "LinkedIn", up: 127, color: "yellow" },
            { site_name: "Reddit", up: 0, color: "red" },
            { site_name: "TikTok", up: 127, color: "red" },
            { site_name: "Pinterest", up: 127, color: "black" },
            { site_name: "Snapchat", up: 127, color: "red" },
            { site_name: "WhatsApp", up: 127, color: "yellow" },
            { site_name: "Telegram", up: 127, color: "red" },
          ],
        },
      ],
    },
    {
      config_name: "Germany Websockets",
      chart: [
        {
          timestamp: "13.13",
          slots: [
            { site_name: "Facebook", up: 127, color: "red" },
            { site_name: "X", up: 127, color: "red" },
            { site_name: "Instagram", up: 127, color: "red" },
            { site_name: "LinkedIn", up: 127, color: "yellow" },
            { site_name: "Reddit", up: 0, color: "red" },
            { site_name: "TikTok", up: 127, color: "red" },
            { site_name: "Pinterest", up: 127, color: "black" },
            { site_name: "Snapchat", up: 127, color: "red" },
            { site_name: "WhatsApp", up: 127, color: "yellow" },
            { site_name: "Telegram", up: 127, color: "red" },
          ],
        },
      ],
    },
  ],
};
